workflows:
  pub-dev-publishing:
    name: Publishing to pub.dev
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      vars:
        PUB_DEV_CREDENTIALS

    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
      - name: Publish to pub.dev
        script: |
          echo $PUB_DEV_CREDENTIALS > "$FLUTTER_ROOT/.pub-cache/credentials.json"
          flutter pub publish --dry-run
          flutter pub publish -f