name: flutter_nude_detector
description: flutter_nudity_detection is a comprehensive Flutter package that enables developers to detect nudity content in images with ease. It leverages the power of advanced machine learning algorithms to accurately identify and flag explicit or adult content within images, ensuring a safer and more secure user experience.
version: 0.0.4
repository: https://github.com/piekarskipiotr/flutter-nude-detector

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_image_labeling: ">=0.5.0 <0.9.0"
  path: ^1.8.2
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ">=3.1.0 <6.0.0"
